Feat/research
olgalatkina/itmo-lab pull request #10
Opened 2022-03-30 19:28 UTC by VladimirIvancha

Просьба проверить верстку блока Research

2022-03-30 22:04 UTC, olgalatkina commented on index.html
> +      <section class="research" id="research">
Всё содержимое секции должно быть обёрнуто в контейнер/враппер, чтобы при переполнении заголовок не выпадал за пределы секции

2022-03-30 22:05 UTC, olgalatkina commented on index.html
> +        <h2 class="research__title">INDUSTRIAL AI RESEARCH LAB</h2>
uppercase у заголовка прописывается в css, не в разметке

2022-03-30 22:07 UTC, olgalatkina commented on index.html
> +          <div class="research__wrapper">
враппер/контейнер должен ограничивать всё содержимое, а не часть контента

2022-03-30 22:07 UTC, olgalatkina commented on index.html
> +              <img class="research__layout" src="./images/lab/layer-w768-project.png" alt="">
если используется тег img, нужно заполнить alt

2022-03-30 22:19 UTC, olgalatkina commented on index.html
> +            <div class="research__description">
текст должен тянуться на всю ширину контейнера (researsh_02.jpg)

2022-03-30 22:22 UTC, olgalatkina commented on index.html
> +              <p class="research__text">Центр национальной технологической инициативы (НТИ), получивший государственную поддержку по&nbsp;направлению &laquo;Технологии машинного обучения и&nbsp;когни
На макете шрифт первого абзац жирнее, чем второго абзаца

2022-03-30 22:26 UTC, olgalatkina commented on index.html
> +          <div class="research__cards">
для однотипных компонентов лучше использовать ul>li

2022-03-30 22:27 UTC, olgalatkina commented on index.html
> +            <div class="research__card research__card_active">
это состояние должно отрабатывать по ховеру, в макете есть ссылка на поведение карточки

2022-03-30 22:30 UTC, olgalatkina commented on index.html
> +              <button class="research__card-button research__card-button_active">Подробнее</button>
по ховеру на карточке у кнопки нет бордера

2022-03-30 22:58 UTC, olgalatkina commented on index.html
> +        <div class="research__popup">
нужен класс для показа попапа

2022-03-30 22:58 UTC, olgalatkina requested changes
- Если добавляешь картинки в репу, то их сначала надо оптимизировать (https://tinypng.com/ для .jpg/.png и https://jakearchibald.github.io/svgomg/).
- Не стоит использовать 3 размера одной картинки) Всё управление размерами через css. 
- Лишние картинки надо удалить.

2022-04-09 14:59 UTC, VladimirIvancha commented on index.html
> +          <div class="research__cards">
первое исправил, второе и третье - не стал, т.к. auto-fit, minmax отлично отрабатывают состояние на странице в промежутке между ширнами 320 px и 768 px. Либо я не правильно понял твой коммент

2022-04-10 10:20 UTC, olgalatkina commented on index.html
> +    <script src="./scripts/research.js"></script>
Володя, скрипты не стоит подключать посередине index.html, либо в `head`, либо перед закрытием тега `body`
у нас именно второй вариант, подключаем мы ОДИН файл index.js а уже в него импортируются нужные модули (файлы секций)
Посмотри пожалуйста в структуре проекта папку `scripts` и поизучай реализацию других секций

2022-04-10 15:04 UTC, Smolib commented on index.html
> +  <section class="research" id="research">
На большом разрешении забылась вот эта штучка. 
![Screenshot_1695](https://user-images.githubusercontent.com/94445186/162625950-e79a9a66-a751-46c5-adb0-a187c56c3088.jpg)

2022-04-10 15:07 UTC, Smolib commented on index.html
> +    <div class="research__container">
На разрешении чуть ниже 1440 вид блока слишком узкий, не соответствует общему стилю. Можно поправить media или подумать над динамическим размером блоков и отступов.
![Screenshot_1696](https://user-images.githubusercontent.com/94445186/162626068-13c46a3d-8e3f-4c44-8ab3-9bf5b9651972.jpg)

2022-04-10 15:09 UTC, Smolib commented on index.html
> +            <img class="research__layout" src="./images/lab/layer-w768-project.png" alt="Коллаж из открытых страниц с проектами фоном">
Тут все-таки однозначно напрашивается background, а не img. Семантически это фон, никак не картинка.

2022-04-10 15:10 UTC, Smolib commented on index.html
> +              <img class="research__card-icon" src="./images/lab/research-icon-project.svg" alt="Линейка и карандаш">
Тут тоже можно через background, но уже не настолько однозначно. )

2022-04-10 15:11 UTC, Smolib commented on index.html
> +    <div class="research__popup">
Насколько я вижу - анимация нормально отрабатывать при текущих стилях не будет. Но это проще будет настроить уже с js-ом, чтобы видеть сразу.

2022-04-10 15:14 UTC, Smolib commented on index.html
> +          <li class="research__card">
Я не уверена, что здесь нужен cursor: pointer на всю карточку. У нас есть кнопка подробнее, по идее только она должна вызывать срабатывание попапа, и только она должна быть с pointer.

2022-04-10 15:33 UTC, Smolib commented on index.html
> +    <div class="research__popup">
В целом попап надо бы переделать. Верстать абсолютами плохое решение. Вот пример, почему это так:
![Screenshot_1697](https://user-images.githubusercontent.com/94445186/162626922-49652beb-55ef-4c7b-ba9f-b3f2a17afc30.jpg)
+ попробуй воспользоваться grid-ом и четко каждому блоку задавать позицию, меняя эту самую позицию (или убирая блок совсем) при изменении экрана.
+ также есть проблема с разрешением чуть ниже 1440, опять же, лучше чтобы блок умел динамично растягиваться.
+ еще стоит продумать то, что мы обсуждали на созвонах - добавить скролл для текста при переполнении. Потому что даже сейчас блок уже еле влезает на экран, надо подумать что будет при бОльшем тексте.

2022-04-11 21:04 UTC, VladimirIvancha commented on index.html
> +    <div class="research__popup">
я пока оставил, если ты не против. потом посмотрим как будет с js работать

2022-04-12 16:09 UTC, Smolib commented on index.html
> +      <ul class="research__popup-container">
А зачем здесь переход на список?) Это совсем не по семантике, тут нет списка, он тут не нужен. Первоначальный div был куда логичнее.
При переполнении теперь есть скролл - отлично. )

2022-04-12 16:10 UTC, Smolib commented on index.html
>              <ul class="research__popup-list">
Вот это - настоящий список, тут все хорошо. )

2022-04-12 16:13 UTC, Smolib commented on index.html
> +            <img class="research__photo-main" src="./images/lab/image 35.png" alt="Мужчины работают в светлом офисе за компьютерами">
Теперь это картинки по семантике, отлично. )
На мобильном разрешении немного не попадает в высоту макета (по макету картинка обрезается до 180 с той же шириной).

2022-04-12 16:22 UTC, Smolib commented on index.html
> +            <img class="research__photo-main" src="./images/lab/image 35.png" alt="Мужчины работают в светлом офисе за компьютерами">
Также на большом разрешении эта же картинка ломает верстку из-за min-width.

2022-04-12 16:28 UTC, Smolib commented on index.html
>            <button type="button" aria-label="закрыть" class="research__popup-close-button"></button>
Крестик катается вместе с заголовком и поэтому часто оказывается в корявых местах.
![Screenshot_1705](https://user-images.githubusercontent.com/94445186/163009305-11fd89b3-d9d2-4da5-85a5-3eceb6adba8d.jpg)
Самым простым способом решения может быть убиранием у popup-wrapper-а align-self, тогда кнопка вместе с заголовком прижмется к верху. Либо вынести кнопку через абсолют и закрепить за ней постоянное место (надо не забыть в таком случае продумать такую верстку, чтобы заголовок на нее не залезал никогда).

2022-04-13 08:46 UTC, olgalatkina approved these changes

2022-04-13 16:12 UTC, merged