Feat/publications render cards
olgalatkina/itmo-lab pull request #35
Opened 2022-04-09 19:17 UTC by kamelyanov

Посмотрите плиз, у кого будет время 

Насчет странного поведения карточек при ховере: когда писал код, заметил, что если вручную добавлять класс на бокс с соц.сетями, то он занимал положение как раз под карточкой, но когда функция дописывает этот класс, все нормально. Если будет проявляться, подправим

2022-04-09 19:18 UTC, kamelyanov commented on index.html
>      </div>
@olgalatkina все-таки заменил ссылку на кнопку)))

2022-04-09 19:43 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._tooltip.classList.toggle('tooltip_active');
тут, скорее, должен быть `classList.add`, используется либо пара `add/remove`, либо toggle

2022-04-09 19:44 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._tooltip = this._element.querySelector('.tooltip');
а зачем ты здесь находил `this._tooltip`?

2022-04-09 19:48 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._imageCard.alt = this._data.title;
исключительно на твоё усмотрение)) с `this._imageCard` ты работал выше, группировать лучше не по входным данным, а по элементам с которыми работешь (вкусовщина!)

2022-04-09 19:57 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._autorsCard.textContent = this._data.autors;
до чего техника дошла😂 ты содержанием элемента сделал **массив** и браузер с этим справился... неслыханно!
я бы делала что-то вроде `this._data.autors.join(', ')`

2022-04-09 20:06 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +
лишняя строчка)

2022-04-09 20:08 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._setEventListeners();
на твоё усмотрение)) нет необходимости навешивать обработчики в конце, можно сразу после вызова `this._getElement();`

2022-04-09 20:16 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    return this._element;
а где прописывание ссылок в тултипе? 
(надо вообще почитать, как шарить что-либо в соцсети, потом нам расскажешь👌)

2022-04-09 20:19 UTC, olgalatkina requested changes
Как будешь прикручивать слайдер, надо будет поправить контейнер, сейчас очень странно смотрятся 2 карточки посреди пустого пространства на 1430px

2022-04-09 20:31 UTC, olgalatkina commented on index.html
>      </div>
стоит добавить `type="button"` кнопке

2022-04-09 20:44 UTC, kamelyanov commented on scripts/publications/PublicationsCard.js
> +    this._tooltip.classList.toggle('tooltip_active');
toggle если мы нажимаем на кнопку открыть тултип (тогда при нажатии он убирается или добавляется), а если мы убираем курсор с карточки, то класс удаляется, если он был и не происходит показ карточки, если ее не было. 
Если делать `add/remove` то, чтобы убрать открый тултип придется убрать курсор с карточки, в общем я думаю юзабильнее будет так оставить

2022-04-09 20:47 UTC, kamelyanov commented on scripts/publications/PublicationsCard.js
> +    this._tooltip = this._element.querySelector('.tooltip');
мм, чтобы отдельно не находить в методах `showToolTip` и ` hideToolTip` , перенес в `generate()`

2022-04-09 20:48 UTC, kamelyanov commented on scripts/publications/PublicationsCard.js
> +    this._imageCard.alt = this._data.title;
наверно все-таки соглашусь, что так правильнее))

2022-04-09 20:50 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._tooltip.classList.toggle('tooltip_active');
сргласна!

2022-04-09 20:52 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +    this._tooltip = this._element.querySelector('.tooltip');
и что?

2022-04-09 20:55 UTC, kamelyanov commented on scripts/publications/PublicationsCard.js
> +    this._autorsCard.textContent = this._data.autors;
да, согласен, что-то не посмотрел что в моковых данных авторы это у нас массив в данном случае) переделываем в строку)

2022-04-09 20:56 UTC, kamelyanov commented on scripts/publications/PublicationsCard.js
> +    this._setEventListeners();
согласен, так будет читабильнее

2022-04-09 22:17 UTC, kamelyanov commented
насчет поделиться, я нашел как это делается, настройки окон оставил стандартные, сделал для вк и телеги, сейчас в слак скину как делал. Подправил моковые данные моей секции, оказывается там одна общая ссылка на страницу для всех, а вот конкретно под каждую соц.сеть разные параметры. Ну и переделал немного html - всё-таки это все кнопки, и не нужно ставить заглушку.

2022-04-10 10:05 UTC, olgalatkina commented
ну чтож, поздравляю тебя с первой битвой в "holy war" кнопки или ссылки😂
даже с самим собой это увлекательно))
PR принимаю, надо только в моках вычистить из текстов `&nbsp;` - они, к сожалению, прописались прямо в текст как есть

2022-04-10 10:06 UTC, olgalatkina commented on scripts/publications/PublicationsCard.js
> +  _shareSocials() {
круто, что разобрался!

2022-04-10 10:06 UTC, olgalatkina approved these changes

2022-04-10 10:27 UTC, merged